- hosts: staging
  become: yes
  tasks:

    - name: Update server packages
      apt:
        update_cache: yes

    - name: Install PHP
      apt:
        name: php
        state: present

    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present

    - name: Sync project to server
      synchronize:
        src: "{{ playbook_dir }}/../"
        dest: /var/www/html/
        delete: yes
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=ansible"
          - "--exclude=.github"
